import './globals.css'
import localFont from 'next/font/local'

export const metadata = {
  title: '🍀 TFT 🍀',
  description: 'Generated by create next app',
  viewport: 'width=device-width, initial-scale=1.0',
}

//import the two fonts from the public/assets/fonts folder
const beaufort = localFont({
  src: [
    {
      path: '../public/assets/fonts/BeaufortforLOL-Bold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../public//assets/fonts/BeaufortforLOL-BoldItalic.otf',
      weight: '700',
      style: 'italic',
    },
    {
      path: '../public//assets/fonts/BeaufortforLOL-Heavy.otf',
      weight: '900',
      style: 'normal',
    },
    {
      path: '../public//assets/fonts/BeaufortforLOL-HeavyItalic.otf',
      weight: '900',
      style: 'italic',
    },
    {
      path: '../public//assets/fonts/BeaufortforLOL-Italic.otf',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../public//assets/fonts/BeaufortforLOL-Light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public//assets/fonts/BeaufortforLOL-LightItalic.otf',
      weight: '300',
      style: 'italic',
    },
    {
      path: '../public//assets/fonts/BeaufortforLOL-Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public//assets/fonts/BeaufortforLOL-MediumItalic.otf',
      weight: '500',
      style: 'italic',
    },
    {
      path: '../public//assets/fonts/BeaufortforLOL-Regular.otf',
      weight: '400',
      style: 'normal',
    }
  ]
})

const spiegel = localFont({
  src: [
    {
      path: '../public/assets/fonts/Spiegel-Bold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../public/assets/fonts/Spiegel-BoldItalic.otf',
      weight: '700',
      style: 'italic',
    },
    {
      path: '../public/assets/fonts/Spiegel-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/assets/fonts/Spiegel-RegularItalic.otf',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../public/assets/fonts/Spiegel-SemiBold.otf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../public/assets/fonts/Spiegel-SemiBoldItalic.otf',
      weight: '600',
      style: 'italic',
    }
  ]  
})


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
      <html lang="fr" className={`${beaufort.className} ${spiegel.className}`}>
        <body>{children}</body>
      </html>
    
  )
}